### ISSUE TITLE
不能再一个页面多次引入

### ISSUE THREAD

**Issue by ldzdz** [supervons/react-native-supervons-custom-keyboard#3]
在同一个页面引入多个此标签，如新密码，确认密码。在输入新密码的时候，确认密码也会同步输入值。

**Comment by supervons** [comment]
@ldzdz  hello！你好，欢迎使用这个键盘组件，感谢反馈，确实有这个问题，做了一下修复。1.4.1版本已修复，更新方式如下：

```npm
npm install react-native-supervons-custom-keyboard@1.4.1
```


同页面使用多个增加一个keyName即可！
![image](https://user-images.githubusercontent.com/31637849/115575456-28323b80-a2f5-11eb-8904-17f06bae4c09.png)
