### ISSUE TITLE
没有@符号

### ISSUE THREAD

**Issue by lhhhhhhhhh** [supervons/react-native-supervons-custom-keyboard#6]
没看到@符号，版本1.4.5
![Uploading b964b98c728fd31eb4dee6fe71a6336.jpg…]()

**Comment by supervons** [comment]
已修复，新增符号 '@、¥、€'，更新到 `1.4.6` 版本使用：
```
npm install react-native-supervons-custom-keyboard@1.4.6
```
@lhhhhhhhhh 
提交请查看 f40b764
